### ISSUE TITLE
汽车之家爬虫运行报错

### ISSUE THREAD

**Issue by polichan** [LeoLin9527/ZSpider#5]
Log：
```plain
**Traceback (most recent call last):
  File "E:/ZSpider-master/03-CarHomeConfig/run_the_spider.py", line 135, in <module>
    carHome.run()
  File "E:/ZSpider-master/03-CarHomeConfig/run_the_spider.py", line 126, in run
    self.modify_run_js(config_js, car_config_def, 1)
  File "E:/ZSpider-master/03-CarHomeConfig/run_the_spider.py", line 60, in modify_run_js
    car_info_dict = self.js_exec(configJs, car_config_def)
  File "E:/ZSpider-master/03-CarHomeConfig/run_the_spider.py", line 82, in js_exec
    words = ctx.call('get_words')
  File "D:\Program Files\Python\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "D:\Program Files\Python\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "D:\Program Files\Python\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "D:\Program Files\Python\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "D:\Program Files\Python\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "D:\Program Files\Python\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: Error: Cannot find module 'jsdom'
Require stack:
- E:\ZSpider-master\03-CarHomeConfig\[stdin]**
```
看报错应该是 jsdom 没有安装的原因，我尝试了下 ``npm install jsdom -g`` 但是不行，请问能否指点一下如何解决，多谢了。

**Comment by polichan** [comment]
解决了，在项目根目录安装 ``jsdom``，然后修改 ``subprocess.py`` 中的 encoding 为 utf-8。
